name: vouchers
description: "Gerador de Vouchers."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  file_picker: ^8.0.4
  csv: ^6.0.0
  pdf: ^3.10.8
  open_filex: ^4.4.0
  path_provider: ^2.1.3
  universal_html: ^2.2.4
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7


icons_launcher:
  image_path: "assets/logo.jpg"
  platforms:
    windows:
      enable: true
    web:
      enable: true

flutter:
  uses-material-design: true
