name: vouchers
description: "Gerador de Vouchers."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  file_picker: ^13.1.0
  csv: ^8.0.0
  pdf: ^3.13.0
  open_filex: ^4.7.0
  path_provider: ^2.1.6
  universal_html: ^2.3.0
  window_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  icons_launcher: ^3.1.0


icons_launcher:
  image_path: "assets/logo.jpg"
  platforms:
    windows:
      enable: true
    web:
      enable: true

flutter:
  uses-material-design: true
